import RequestProject.Section4DoubleBoost

/-!
# Section 4: preparation for the final contradiction, all three cases

This file proves the estimate

`F(x-1) + F(a-2) + F(x+1) ≤ x + t + F(2) - 3`

in all three cases of the paper's final case split. The geometric sumset and
difference-set packings are recorded in the cumulative forms in which they enter
the calculation; the lemmas below carry out their cancellation, prove the
numerical contradiction needed in Case 3, and establish that the three order
alternatives are exhaustive.
-/

open MeasureTheory Set
open scoped Pointwise

noncomputable section

namespace ProductFree

variable {A : Set ℝ}

/-
In Case 1, cancellation across the mass-free gap `(u',v')` turns the
Brunn--Minkowski difference-set packing into the required increment bound.
-/
lemma prep_u_small_case_one_increment
    {x u' v' : ℝ}
    (hpacking :
      (cum A (x + 1) - cum A v') + (cum A u' - cum A (x - 1)) + cum A 2 ≤ 1)
    (hgapMass : cum A u' = cum A v') :
    cum A (x + 1) - cum A (x - 1) + cum A 2 ≤ 1 := by
  linarith

/-
**Case 1** (`v > y`).  Here the gap gives `F(y)=F(2)`.  Combining the
preceding increment estimate with `diff eq` proves the target (in fact strictly,
because `y>3`).
-/
lemma prep_u_small_case_one
    {a x y t : ℝ}
    (hxy : a + y = x + 1) (hy : 3 < y)
    (hyMass : cum A y = cum A 2)
    (hdiff : 2 * cum A (x - 1) + cum A (a - 2) ≤
      a - 2 + t + 2 * cum A y)
    (hincrement : cum A (x + 1) - cum A (x - 1) + cum A 2 ≤ 1) :
    cum A (x - 1) + cum A (a - 2) + cum A (x + 1) ≤
      x + t + cum A 2 - 3 := by
  linarith

/-
In Case 2, the two packing estimates, the identity `F(v)=F(2)`, and the
lower bound on `F(v-y+2)` imply the increment estimate used in the final
calculation.
-/
lemma prep_u_small_case_two_increment
    {x y v : ℝ}
    (hcombined : cum A (x + 1) - cum A (x - 1) + cum A (v - y + 2) +
      2 * (cum A y - cum A v) ≤ 1)
    (hvMass : cum A v = cum A 2)
    (hlower : cum A 2 - (y - 3) ≤ cum A (v - y + 2)) :
    cum A (x + 1) - cum A (x - 1) + 2 * cum A y ≤
      y - 2 + cum A 2 := by
  linarith

/-
**Case 2** (`v ≤ y` and `v+a ≥ v'`).  Adding the case-specific increment
bound to `diff eq` gives exactly the desired preparation inequality.
-/
lemma prep_u_small_case_two
    {a x y t : ℝ}
    (hxy : a + y = x + 1)
    (hdiff : 2 * cum A (x - 1) + cum A (a - 2) ≤
      a - 2 + t + 2 * cum A y)
    (hincrement : cum A (x + 1) - cum A (x - 1) + 2 * cum A y ≤
      y - 2 + cum A 2) :
    cum A (x - 1) + cum A (a - 2) + cum A (x + 1) ≤
      x + t + cum A 2 - 3 := by
  linarith

/-
Case 1 directly from the paper's difference-set packing and the absence of
mass in `(u',v')`.
-/
theorem prep_u_small_first_case
    {a x y t u' v' : ℝ}
    (hxy : a + y = x + 1) (hy : 3 < y)
    (hyMass : cum A y = cum A 2)
    (hdiff : 2 * cum A (x - 1) + cum A (a - 2) ≤
      a - 2 + t + 2 * cum A y)
    (hpacking :
      (cum A (x + 1) - cum A v') + (cum A u' - cum A (x - 1)) + cum A 2 ≤ 1)
    (hgapMass : cum A u' = cum A v') :
    cum A (x - 1) + cum A (a - 2) + cum A (x + 1) ≤
      x + t + cum A 2 - 3 := by
  grind

/-
Case 2 directly from the combined difference- and sumset packing estimate.
-/
theorem prep_u_small_second_case
    {a x y t v : ℝ}
    (hxy : a + y = x + 1)
    (hdiff : 2 * cum A (x - 1) + cum A (a - 2) ≤
      a - 2 + t + 2 * cum A y)
    (hcombined : cum A (x + 1) - cum A (x - 1) + cum A (v - y + 2) +
      2 * (cum A y - cum A v) ≤ 1)
    (hvMass : cum A v = cum A 2)
    (hlower : cum A 2 - (y - 3) ≤ cum A (v - y + 2)) :
    cum A (x - 1) + cum A (a - 2) + cum A (x + 1) ≤
      x + t + cum A 2 - 3 := by
  grind +suggestions

/-
The numerical contradiction used at the start of Case 3. Here `d = y-v`,
`left` and `right` are the masses on the two pieces of `[a,b]`, and `jump` is
`F(x+1)-F(x)`. It proves the paper's intermediate conclusion `s ≤ y-v`.
-/
lemma prep_u_small_case_three_gap_numeric
    {s t d left right jump : ℝ}
    (hpack : left + jump ≤ d)
    (hjump : 1 - t < jump)
    (htotal : (s + t) / 2 < left + right)
    (hright : right ≤ s - d)
    (hst : s + t ≤ 2) : False := by
  grind +qlia

/-
Adding the two Case 3 packing estimates. The first comes from the mass-free
interval ending at `v+a`; the second comes from the sumset generated by `[v,y]`.
-/
lemma prep_u_small_case_three_increment
    {x y v va q : ℝ}
    (hfirst : cum A va - cum A (x - 1) + cum A q ≤ va - x)
    (hsum : 2 * (cum A y - cum A v) + (cum A (x + 1) - cum A va) ≤
      x + 1 - va)
    (hvMass : cum A v = cum A 2)
    (hlower : cum A 2 - (y - 3) ≤ cum A q) :
    cum A (x + 1) - cum A (x - 1) + 2 * cum A y ≤
      y - 2 + cum A 2 := by
  linarith

/-
**Case 3** (`v ≤ y` and `v+a < v'`).
-/
theorem prep_u_small_third_case
    {a x y t v va q : ℝ}
    (hxy : a + y = x + 1)
    (hdiff : 2 * cum A (x - 1) + cum A (a - 2) ≤
      a - 2 + t + 2 * cum A y)
    (hfirst : cum A va - cum A (x - 1) + cum A q ≤ va - x)
    (hsum : 2 * (cum A y - cum A v) + (cum A (x + 1) - cum A va) ≤
      x + 1 - va)
    (hvMass : cum A v = cum A 2)
    (hlower : cum A 2 - (y - 3) ≤ cum A q) :
    cum A (x - 1) + cum A (a - 2) + cum A (x + 1) ≤
      x + t + cum A 2 - 3 := by
  convert prep_u_small_case_two _ _ _ using 1;
  exact y;
  · linarith;
  · grind;
  · convert prep_u_small_case_three_increment hfirst hsum hvMass hlower using 1

/-
The three alternatives in the paper are exhaustive.
-/
theorem prep_u_small_all_cases
    {a x y t u' v' v : ℝ}
    (hxy : a + y = x + 1) (hy : 3 < y)
    (hdiff : 2 * cum A (x - 1) + cum A (a - 2) ≤
      a - 2 + t + 2 * cum A y)
    (hcase1 : y < v →
      cum A y = cum A 2 ∧
      ((cum A (x + 1) - cum A v') +
        (cum A u' - cum A (x - 1)) + cum A 2 ≤ 1) ∧
      cum A u' = cum A v')
    (hcase2 : v ≤ y → v' ≤ v + a →
      (cum A (x + 1) - cum A (x - 1) + cum A (v - y + 2) +
        2 * (cum A y - cum A v) ≤ 1) ∧
      cum A v = cum A 2 ∧
      cum A 2 - (y - 3) ≤ cum A (v - y + 2))
    (hcase3 : v ≤ y → v + a < v' →
      (cum A (v + a) - cum A (x - 1) + cum A (v - y + 2) ≤ v + a - x) ∧
      (2 * (cum A y - cum A v) +
        (cum A (x + 1) - cum A (v + a)) ≤ x + 1 - (v + a)) ∧
      cum A v = cum A 2 ∧
      cum A 2 - (y - 3) ≤ cum A (v - y + 2)) :
    cum A (x - 1) + cum A (a - 2) + cum A (x + 1) ≤
      x + t + cum A 2 - 3 := by
  grind

end ProductFree